apiVersion: v1
kind: Service
metadata:
  name: pwc-service
  labels:
    app: pwc-app
spec:
  type: LoadBalancer  # Creates an AWS ALB
  selector:
    app: pwc-app
  ports:
  - protocol: TCP
    port: 80           # External port for the service
    targetPort: 5000   # Flask listens on port 5000
